# Generated by Django 5.0 on 2023-12-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('Sname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Slocation', models.CharField(max_length=50)),
                ('Sprincipal', models.CharField(max_length=50)),
            ],
        ),
    ]
